/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.AGENDAMENTOS DROP CONSTRAINT FORNECEDORES_AGENDAMENTOS_FK;
ALTER TABLE LABDATABASE.AGENDAMENTOS DROP CONSTRAINT CLIENTES_AGENDAMENTOS_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.FORNECEDORES;
DROP TABLE LABDATABASE.CLIENTES;
DROP TABLE LABDATABASE.AGENDAMENTOS;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.FORNECEDORES (
                CNPJ VARCHAR2(14) NOT NULL,
                RAZAO_SOCIAL VARCHAR2(255) NOT NULL,
                NOME_FANTASIA VARCHAR2(255) NOT NULL,
                CONSTRAINT FORNECEDORES_PK PRIMARY KEY (CNPJ)
);

CREATE TABLE LABDATABASE.CLIENTES (
                CPF VARCHAR2(11) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT CLIENTES_PK PRIMARY KEY (CPF)
);

CREATE TABLE LABDATABASE.AGENDAMENTOS (
                CODIGO_AGENDAMENTO NUMBER NOT NULL,
                DATA_AGENDAMENTO DATE NOT NULL,
                CPF VARCHAR2(11) NOT NULL,
                CNPJ VARCHAR2(14) NOT NULL,
                CONSTRAINT AGENDAMENTOS_PK PRIMARY KEY (CODIGO_AGENDAMENTO)
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.AGENDAMENTOS ADD CONSTRAINT FORNECEDORES_AGENDAMENTOS_FK
FOREIGN KEY (CNPJ)
REFERENCES LABDATABASE.FORNECEDORES (CNPJ)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.AGENDAMENTOS ADD CONSTRAINT CLIENTES_AGENDAMENTOS_FK
FOREIGN KEY (CPF)
REFERENCES LABDATABASE.CLIENTES (CPF)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.FORNECEDORES TO LABDATABASE;
GRANT ALL ON LABDATABASE.CLIENTES TO LABDATABASE;
GRANT ALL ON LABDATABASE.AGENDAMENTOS TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;