/*Apaga os relacionamentos*/
ALTER TABLE LABDATABASE.MEDICO DROP CONSTRAINT FORNECEDORES_MEDICO_FK;
ALTER TABLE LABDATABASE.MEDICO DROP CONSTRAINT PACIENTES_MEDICO_FK;
ALTER TABLE LABDATABASE.ITENS_MEDICO DROP CONSTRAINT MEDICO_ITENS_MEDICO_FK;
ALTER TABLE LABDATABASE.ITENS_MEDICO DROP CONSTRAINT PRODUTOS_ITENS_MEDICO_FK;

/*Apaga as tabelas*/
DROP TABLE LABDATABASE.FORNECEDORES;
DROP TABLE LABDATABASE.PACIENTES;
DROP TABLE LABDATABASE.MEDICO;

/*Apaga as sequences*/
DROP SEQUENCE LABDATABASE.MEDICO_CODIGO_MEDICO_SEQ;

/*Cria as tabelas*/
CREATE TABLE LABDATABASE.PACIENTES (
                CPF VARCHAR2(11) NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT PACIENTES_PK PRIMARY KEY (CPF)
);

CREATE TABLE LABDATABASE.MEDICO (
                CODIGO_MEDICO NUMBER NOT NULL,
                CPF VARCHAR2(11) NOT NULL,
                CNPJ VARCHAR2(14) NOT NULL,
                CONSTRAINT MEDICO_PK PRIMARY KEY (CODIGO_MEDICO)
);

/*Cria as sequences*/
CREATE SEQUENCE LABDATABASE.MEDICO_CODIGO_MEDICO_SEQ;

/*Cria os relacionamentos*/
ALTER TABLE LABDATABASE.MEDICO ADD CONSTRAINT PACIENTES_MEDICO_FK
FOREIGN KEY (CPF)
REFERENCES LABDATABASE.PACIENTES (CPF)
NOT DEFERRABLE;

ALTER TABLE LABDATABASE.ITENS_MEDICO ADD CONSTRAINT MEDICO_ITENS_MEDICO_FK
FOREIGN KEY (CODIGO_MEDICO)
REFERENCES LABDATABASE.MEDICO (CODIGO_MEDICO)
NOT DEFERRABLE;

/*Garante acesso total as tabelas*/
GRANT ALL ON LABDATABASE.FORNECEDORES TO LABDATABASE;
GRANT ALL ON LABDATABASE.PACIENTES TO LABDATABASE;
GRANT ALL ON LABDATABASE.MEDICO TO LABDATABASE;
GRANT ALL ON LABDATABASE.PRODUTOS TO LABDATABASE;
GRANT ALL ON LABDATABASE.ITENS_MEDICO TO LABDATABASE;

ALTER USER LABDATABASE quota unlimited on USERS;