/*INSERE DADOS NA TABELA DE AGENDAMENTOS E ITENS*/
DECLARE
  VCOD_AGENDAMENTO NUMBER;
BEGIN
  VCOD_AGENDAMENTO := LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.AGENDAMENTOS VALUES(VCOD_AGENDAMENTO,    /*CODIGO_AGENDAMENTO*/
                             SYSDATE,        /*DATA_AGENDAMENTO*/
                             '43201234567',  /*CPF*/
                             '12855579797'/*CNPJ*/
                             );

END;
--
DECLARE
  VCOD_AGENDAMENTO NUMBER;
BEGIN
  VCOD_AGENDAMENTO := LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.AGENDAMENTOS VALUES(VCOD_AGENDAMENTO,    /*CODIGO_AGENDAMENTO*/
                             SYSDATE,        /*DATA_AGENDAMENTO*/
                             '01234567891',  /*CPF*/
                             '012345678912'/*CNPJ*/
                             );
END;
--
DECLARE
  VCOD_AGENDAMENTO NUMBER;
  VCOD_ITEM_AGENDAMENTO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_AGENDAMENTO := LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.AGENDAMENTOS VALUES(VCOD_AGENDAMENTO,    /*CODIGO_AGENDAMENTO*/
                             SYSDATE,        /*DATA_AGENDAMENTO*/
                             '87654320123',  /*CPF*/
                             '12855579796'/*CNPJ*/
                             );
  
END;
--
DECLARE
  VCOD_AGENDAMENTO NUMBER;
  VCOD_ITEM_AGENDAMENTO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_AGENDAMENTO := LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.AGENDAMENTOS VALUES(VCOD_AGENDAMENTO,    /*CODIGO_AGENDAMENTO*/
                             SYSDATE,        /*DATA_AGENDAMENTO*/
                             '32012345678',  /*CPF*/
                             '12855579795'/*CNPJ*/
                             );
                                  
END;
--
DECLARE
  VCOD_AGENDAMENTO NUMBER;
  VCOD_ITEM_AGENDAMENTO NUMBER;
  VCOD_PRODUTO NUMBER;
BEGIN
  VCOD_AGENDAMENTO := LABDATABASE.AGENDAMENTOS_CODIGO_AGENDAMENTO_SEQ.NEXTVAL;
  
  INSERT INTO LABDATABASE.AGENDAMENTOS VALUES(VCOD_AGENDAMENTO,    /*CODIGO_AGENDAMENTO*/
                             SYSDATE,        /*DATA_AGENDAMENTO*/
                             '76543201234',  /*CPF*/
                             '12855579794'/*CNPJ*/
                             );
                                  
END;